/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package shulesoft;

import javax.swing.JFrame;
import javax.swing.UIManager;
import studentManagement.*;
import examManagement.*;

/**
 *
 * @author eduhg
 */
public class DashBoard extends javax.swing.JFrame {

    /**
     * Creates new form DashBoard
     */
    public DashBoard() {
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        studentManagementPanel = new javax.swing.JPanel();
        cmdStudentReg = new javax.swing.JButton();
        cmdEditStudent = new javax.swing.JButton();
        cmdViewStudents = new javax.swing.JButton();
        cmdStudentManagement = new javax.swing.JButton();
        cmdExamsManagement = new javax.swing.JButton();
        examsManagementPanel = new javax.swing.JPanel();
        cmdEnterMarks = new javax.swing.JButton();
        cmdMerits = new javax.swing.JButton();
        cmdSubjects = new javax.swing.JButton();
        cmdPromotions = new javax.swing.JButton();
        cmdReportCards = new javax.swing.JButton();
        cmdClasses = new javax.swing.JButton();
        formsContainer = new javax.swing.JDesktopPane();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        cmdLogout = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Shule Soft");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        cmdStudentReg.setText("NEW STUDENT REGISTRATION");
        cmdStudentReg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdStudentRegActionPerformed(evt);
            }
        });

        cmdEditStudent.setText("EDIT STUDENT DETAILS");
        cmdEditStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdEditStudentActionPerformed(evt);
            }
        });

        cmdViewStudents.setText("VIEW REGISTERED STUDENTS");
        cmdViewStudents.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdViewStudentsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout studentManagementPanelLayout = new javax.swing.GroupLayout(studentManagementPanel);
        studentManagementPanel.setLayout(studentManagementPanelLayout);
        studentManagementPanelLayout.setHorizontalGroup(
            studentManagementPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(studentManagementPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(studentManagementPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cmdStudentReg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cmdEditStudent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cmdViewStudents, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        studentManagementPanelLayout.setVerticalGroup(
            studentManagementPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(studentManagementPanelLayout.createSequentialGroup()
                .addComponent(cmdStudentReg, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cmdEditStudent, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cmdViewStudents, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        cmdStudentManagement.setText("STUDENT MANAGEMENT");
        cmdStudentManagement.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdStudentManagementActionPerformed(evt);
            }
        });

        cmdExamsManagement.setText("EXAMS MANAGEMENT");
        cmdExamsManagement.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdExamsManagementActionPerformed(evt);
            }
        });

        cmdEnterMarks.setText("ENTER MARKS");
        cmdEnterMarks.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdEnterMarksActionPerformed(evt);
            }
        });

        cmdMerits.setText("CATS/MERITS");
        cmdMerits.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdMeritsActionPerformed(evt);
            }
        });

        cmdSubjects.setText("SUBJECTS");
        cmdSubjects.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdSubjectsActionPerformed(evt);
            }
        });

        cmdPromotions.setText("CLASS PROMOTIONS");
        cmdPromotions.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdPromotionsActionPerformed(evt);
            }
        });

        cmdReportCards.setText("GENERATE REPORT CARDS");
        cmdReportCards.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdReportCardsActionPerformed(evt);
            }
        });

        cmdClasses.setText("CLASSES AND STREAMS");
        cmdClasses.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdClassesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout examsManagementPanelLayout = new javax.swing.GroupLayout(examsManagementPanel);
        examsManagementPanel.setLayout(examsManagementPanelLayout);
        examsManagementPanelLayout.setHorizontalGroup(
            examsManagementPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(examsManagementPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(examsManagementPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cmdEnterMarks, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cmdMerits, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cmdSubjects, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cmdPromotions, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cmdReportCards, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cmdClasses, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        examsManagementPanelLayout.setVerticalGroup(
            examsManagementPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(examsManagementPanelLayout.createSequentialGroup()
                .addComponent(cmdEnterMarks, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cmdMerits, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cmdSubjects, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cmdClasses, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cmdPromotions, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cmdReportCards, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cmdStudentManagement, javax.swing.GroupLayout.DEFAULT_SIZE, 280, Short.MAX_VALUE)
                    .addComponent(cmdExamsManagement, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(examsManagementPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(studentManagementPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(cmdStudentManagement, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(studentManagementPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cmdExamsManagement, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(examsManagementPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 117, Short.MAX_VALUE))
        );

        formsContainer.setBackground(new java.awt.Color(204, 255, 255));
        formsContainer.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        javax.swing.GroupLayout formsContainerLayout = new javax.swing.GroupLayout(formsContainer);
        formsContainer.setLayout(formsContainerLayout);
        formsContainerLayout.setHorizontalGroup(
            formsContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 438, Short.MAX_VALUE)
        );
        formsContainerLayout.setVerticalGroup(
            formsContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 35, Short.MAX_VALUE)
        );

        cmdLogout.setText("LOGOUT");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(cmdLogout)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cmdLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(formsContainer)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(formsContainer)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        studentManagementPanel.setVisible(false);
        examsManagementPanel.setVisible(false);
    }//GEN-LAST:event_formWindowOpened

    private void cmdStudentManagementActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdStudentManagementActionPerformed
        // TODO add your handling code here:
        if (studentManagementPanel.isVisible()) {
            studentManagementPanel.setVisible(false);
        } else {
            studentManagementPanel.setVisible(true);
            examsManagementPanel.setVisible(false);
        }
    }//GEN-LAST:event_cmdStudentManagementActionPerformed

    private void cmdStudentRegActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdStudentRegActionPerformed
        // TODO add your handling code here:
        studentRegistration studentRegistration = new studentRegistration();
        formsContainer.add(studentRegistration);
        int width = (formsContainer.getWidth() - studentRegistration.getWidth()) / 2;
        int height = (formsContainer.getHeight() - studentRegistration.getHeight()) / 2;
        studentRegistration.setLocation(width, height);
        studentRegistration.show();
    }//GEN-LAST:event_cmdStudentRegActionPerformed

    private void cmdEditStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdEditStudentActionPerformed
        // TODO add your handling code here:
        editStudentDetails editStudentDetails = new editStudentDetails();
        formsContainer.add(editStudentDetails);
        int width = (formsContainer.getWidth() - editStudentDetails.getWidth()) / 2;
        int height = (formsContainer.getHeight() - editStudentDetails.getHeight()) / 2;
        editStudentDetails.setLocation(width, height);
        editStudentDetails.show();
    }//GEN-LAST:event_cmdEditStudentActionPerformed

    private void cmdViewStudentsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdViewStudentsActionPerformed
        // TODO add your handling code here:
        viewStudents viewStudents = new viewStudents();
        formsContainer.add(viewStudents);
        int width = (formsContainer.getWidth() - viewStudents.getWidth()) / 2;
        int height = (formsContainer.getHeight() - viewStudents.getHeight()) / 2;
        viewStudents.setLocation(width, height);
        viewStudents.show();
    }//GEN-LAST:event_cmdViewStudentsActionPerformed

    private void cmdExamsManagementActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdExamsManagementActionPerformed
        // TODO add your handling code here:
        if (examsManagementPanel.isVisible()) {
            examsManagementPanel.setVisible(false);
        } else {
            examsManagementPanel.setVisible(true);
            studentManagementPanel.setVisible(false);
        }
    }//GEN-LAST:event_cmdExamsManagementActionPerformed

    private void cmdEnterMarksActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdEnterMarksActionPerformed
        // TODO add your handling code here:
        enterMarks enterMarks = new enterMarks();
        formsContainer.add(enterMarks);
        int width = (formsContainer.getWidth() - enterMarks.getWidth()) / 2;
        int height = (formsContainer.getHeight() - enterMarks.getHeight()) / 2;
        enterMarks.setLocation(width, height);
        enterMarks.show();
    }//GEN-LAST:event_cmdEnterMarksActionPerformed

    private void cmdMeritsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdMeritsActionPerformed
        // TODO add your handling code here:
        merits merits = new merits();
        formsContainer.add(merits);
        int width = (formsContainer.getWidth() - merits.getWidth()) / 2;
        int height = (formsContainer.getHeight() - merits.getHeight()) / 2;
        merits.setLocation(width, height);
        merits.show();
    }//GEN-LAST:event_cmdMeritsActionPerformed

    private void cmdSubjectsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdSubjectsActionPerformed
        // TODO add your handling code here:
        subjects subjects = new subjects();
        formsContainer.add(subjects);
        int width = (formsContainer.getWidth() - subjects.getWidth()) / 2;
        int height = (formsContainer.getHeight() - subjects.getHeight()) / 2;
        subjects.setLocation(width, height);
        subjects.show();
    }//GEN-LAST:event_cmdSubjectsActionPerformed

    private void cmdPromotionsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdPromotionsActionPerformed
        // TODO add your handling code here:
        classPromotions classPromotions = new classPromotions();
        formsContainer.add(classPromotions);
        int width = (formsContainer.getWidth() - classPromotions.getWidth()) / 2;
        int height = (formsContainer.getHeight() - classPromotions.getHeight()) / 2;
        classPromotions.setLocation(width, height);
        classPromotions.show();
    }//GEN-LAST:event_cmdPromotionsActionPerformed

    private void cmdReportCardsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdReportCardsActionPerformed
        // TODO add your handling code here:
        reportCards reportCards = new reportCards();
        formsContainer.add(reportCards);
        int width = (formsContainer.getWidth() - reportCards.getWidth()) / 2;
        int height = (formsContainer.getHeight() - reportCards.getHeight()) / 2;
        reportCards.setLocation(width, height);
        reportCards.show();
    }//GEN-LAST:event_cmdReportCardsActionPerformed

    private void cmdClassesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdClassesActionPerformed
        // TODO add your handling code here:
        classes classes = new classes();
        formsContainer.add(classes);
        int width = (formsContainer.getWidth() - classes.getWidth()) / 2;
        int height = (formsContainer.getHeight() - classes.getHeight()) / 2;
        classes.setLocation(width, height);
        classes.show();
    }//GEN-LAST:event_cmdClassesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            // Set System L&F
            UIManager.setLookAndFeel(
                    UIManager.getSystemLookAndFeelClassName());
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DashBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DashBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DashBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DashBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DashBoard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cmdClasses;
    private javax.swing.JButton cmdEditStudent;
    private javax.swing.JButton cmdEnterMarks;
    private javax.swing.JButton cmdExamsManagement;
    private javax.swing.JButton cmdLogout;
    private javax.swing.JButton cmdMerits;
    private javax.swing.JButton cmdPromotions;
    private javax.swing.JButton cmdReportCards;
    private javax.swing.JButton cmdStudentManagement;
    private javax.swing.JButton cmdStudentReg;
    private javax.swing.JButton cmdSubjects;
    private javax.swing.JButton cmdViewStudents;
    private javax.swing.JPanel examsManagementPanel;
    private javax.swing.JDesktopPane formsContainer;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel studentManagementPanel;
    // End of variables declaration//GEN-END:variables
}
